plugins {
    id 'net.neoforged.moddev' version '2.0.107'
    id 'java-library'
    id 'maven-publish'
    id "dev.ithundxr.silk" version "0.11.15"
    id 'idea'
    id "me.modmuss50.mod-publish-plugin" version "0.8.3"
}

apply from: "./gradle/java.gradle"
apply from: "gradle/property_loader.gradle"


group = "com.${mod_authors}.${mod_id}"
version = "${minecraft_version}-${mod_version}"
archivesBaseName = mod_id
String gitHash = "${calculateGitHash() + (hasUnstaged() ? "-modified" : "")}"

repositories {
    mavenLocal()
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    // Specify the version of NeoForge to use.
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()

            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        // applies to all the run configs above
        configureEach {

            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    mavenLocal()
    maven { url = "https://maven.createmod.net" } // Create, Ponder, Flywheel
    maven { url = "https://mvn.devos.one/snapshots" } // Registrate
    maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/" } // ForgeConfigAPIPort

    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        name = "ModMaven"
        url = "https://modmaven.dev"
    }

}


dependencies {
    implementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    implementation("net.createmod.ponder:Ponder-NeoForge-${minecraft_version}:${ponder_version}")
    compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraft_version}:${flywheel_version}")
    runtimeOnly("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}")
    implementation("com.tterrag.registrate:Registrate:${registrate_version}")

    compileOnly("mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}")
    // at runtime, use the full JEI jar for NeoForge
    runtimeOnly("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")


}

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [minecraft_version      : minecraft_version,
                             minecraft_version_range: minecraft_version_range,
                             neo_version            : neo_version,
                             neo_version_range      : neo_version_range,
                             loader_version_range   : loader_version_range,
                             mod_id                 : mod_id,
                             mod_name               : mod_name,
                             mod_license            : mod_license,
                             mod_version            : mod_version,
                             mod_authors            : mod_authors,
                             mod_description        : mod_description]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

// Include the output of "generateModMetadata" as an input directory for the build
// this works with both building through Gradle and the IDE.
sourceSets.main.resources.srcDir generateModMetadata
// To avoid having to run "generateModMetadata" manually, make it run on every project reload
neoForge.ideSyncTask generateModMetadata

// Example configuration to allow publishing using the maven-publish plugin
publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.configureEach { task ->
    println "Available task: ${task.name}"
}



jar {
    from('LICENSE.txt') {
        rename { "${it}_${archivesBaseName}" }

    }
    manifest.attributes([
            "MixinConfigs": "createschematicchecker.mixins.json",
            "Git-Hash"    :  gitHash
    ])

}

tasks.register('printReobfJarPath') {
    // 在配置阶段获取所需的属性
    def mod_version = project.findProperty("mod_version") ?: "unknown_version"
    def minecraft_version = project.findProperty("minecraft_version") ?: "unknown_minecraft_version"
    def display_name = project.findProperty("display_name") ?: "unknown_display_name"
    def jarPath = tasks.jar.archiveFile.get().asFile.absolutePath

    // 读取 api.properties 文件
    def properties = new Properties()
    def propertiesFile = file('api.properties')
    if (propertiesFile.exists()) {
        properties.load(new FileInputStream(propertiesFile))
    } else {
        println "api.properties not exist"
    }

    // 在 doLast 中使用局部变量和已加载的属性
    doLast {
        // 使用已存储的属性
        println "Reobfuscated JAR file path: $jarPath"
        // 分割版本信息
        def versionParts = mod_version.split("-")
        println "version = \"$minecraft_version-$mod_version\"\n" +
                "    displayName = \"${display_name}_v${versionParts[0]}_for_Create_v${versionParts[1]}\""

        // 打印 CF_TOKEN 和 MODRINTH_TOKEN
        def cfToken = properties.getProperty("CF_TOKEN", "not found")
        def modrinthToken = properties.getProperty("MODRINTH_TOKEN", "not found")

        println "CF_TOKEN: $cfToken"
        println "MODRINTH_TOKEN: $modrinthToken"
    }
}


publishMods {
    def forge_p = true
    def modrinth_p =  true

    def propertiesFile = file('api.properties')
    def properties = new Properties()
    properties.load(new FileInputStream(propertiesFile))
    def cfTokenGet = properties.getProperty("CF_TOKEN")
    def modrinthTokenGet = properties.getProperty("MODRINTH_TOKEN")


    file =  jar.archiveFile
    changelog = rootProject.file("update/neoforge_${minecraft_version}-${mod_version}.md").text
    type = STABLE
    version = "$minecraft_version-$mod_version"
    def versionParts = mod_version.split("-")
    displayName = "${display_name}_v${versionParts[0]}_for_Create_v${versionParts[1]}"
    modLoaders.add("forge")
    modLoaders.add("neoforge")

    var cfToken = cfTokenGet
    if(cfToken != null) {
        if (forge_p)
        {
            curseforge {
                accessToken = cfTokenGet
                projectId = "${curseforge_id}"
                minecraftVersions.add(minecraft_version)
                clientRequired = true
                serverRequired = true
                requires("create")
                optional("observable")
            }
        }

    }
    var mrToken = modrinthTokenGet
    if(mrToken != null) {
        if (modrinth_p)
        {
            modrinth {
                accessToken = modrinthTokenGet
                projectId = "${modrinth_id}"
                minecraftVersions.add(minecraft_version)
                requires("create")
                optional("observable")
            }
        }
    }
}










// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}



String calculateGitHash() {
    try {
        def output = providers.exec {
            commandLine("git", "rev-parse", "HEAD")
        }
        return output.standardOutput.asText.get().trim()
    } catch (Throwable ignored) {
        return "unknown"
    }
}

boolean hasUnstaged() {
    try {
        def output = providers.exec {
            commandLine("git", "status", "--porcelain")
        }
        String result = output.standardOutput.asText.get().replace("/M gradlew(\\.bat)?/", "").trim()
        if (!result.isEmpty())
            println("Found stageable results:\n ${result}\n")
        return !result.isEmpty()
    } catch (Throwable ignored) {
        return false
    }
}
