plugins {
    id 'idea'
    id 'org.jetbrains.gradle.plugin.idea-ext' version '1.2'
    id 'fabric-loom' version '1.10.5' apply false
}

allprojects {
    repositories {
        maven {
            name = "PinkCatsLocal"
            url = uri("C:/F/Maven")
        }
        mavenCentral()
    }

    configurations.configureEach {
        resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
    }
}

apply from: rootProject.file('gradle/allwork/root.gradle')

tasks.register('runClientAllVersions') {
    group = 'Development'
    description = 'Run the client development environment for all runnable versions.'
    dependsOn ':global:runClientAllVersions'
}

tasks.register('runServerAllVersions') {
    group = 'Development'
    description = 'Run the server development environment for all runnable versions.'
    dependsOn ':global:runServerAllVersions'
}
