plugins {
    id 'idea'
    id 'org.jetbrains.gradle.plugin.idea-ext' version '1.2'
}

allprojects {
    repositories {
        maven {
            name = "PinkCatsLocal"
            url = uri("C:/F/Maven")
        }
        mavenCentral()
    }

    configurations.configureEach {
        resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
    }
}
