# Shared mod metadata for all supported loader/version variants.
publish_version = release
package_name = CreateSchematicChecker
mod_version_base = 1.21.21
torque_api_version = 1.0.0-SNAPSHOT

curseforge_id = 1357430
modrinth_id = ULzrAD1U
mod_id = createschematicchecker
mod_name = Create:Schematic Checker
display_name = CSC

mod_license = GNU LGPL 3.0
mod_group_id = com.Pink_Cats
mod_authors = Pink_Cats
mod_description = A mod for fix all schematic problems from Create and all addons!
