org.gradle.jvmargs=-Xmx3G -Dnet.minecraftforge.gradle.check.certs=false
org.gradle.daemon=false
org.gradle.java.home=C:/Users/19072/.gradle/jdks/openjdk16-hotspot-windows/jdk-16.0.2+7
org.gradle.java.installations.paths=C:/Users/19072/.gradle/jdks/openjdk16-hotspot-windows/jdk-16.0.2+7,C:/Users/19072/.gradle/jdks/temurin11-hotspot-windows/jdk-11.0.30+7
org.gradle.java.installations.auto-download=true
