# Shared mod metadata and mod_version_base are loaded from gradle/csc-common.properties.
supported_create_version = 0.4

minecraft_version = 1.17.1
forge_version = 37.1.1
forge_version_range = [37,)
loader_version_range = [37,)
mapping_channel = official



# create
create_minecraft_version = 1.17.1
flywheel_minecraft_version = 1.17
create_version = mc1.17.1_v0.4+39
flywheel_version = 1.17-0.3.0.24
registrate_version = MC1.17.1-1.0.14
parchment_version = 2021.12.12

# publishing
csc_publish_required_dependencies = create

# gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.logging.level=quiet
